#-------------------------------------------------------------------------------
#
# "test" GitHub Action configuration
#
#-------------------------------------------------------------------------------
---
name: "test"
on:
  - "push"
jobs:
  docker:
    name: "Docker"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the Docker image"
        uses: "actions/checkout@v1"
        run: 'printenv && docker build --build-arg BUILD_DATE="" --build-arg VCS_REF="" --build-arg VERSION="" .'
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Set up Go 1.13"
        uses: "actions/setup-go@v1"
        with:
          go-version: 1.13
        id: "go"

      - name: "Check out code into the Go module directory"
        uses: "actions/checkout@v1"

      - name: "Get dependencies"
        run: "go mod vendor"

      - name: "Test"
        run: "go test ./... -cover"

      - name: "Build"
        run: "go build -v -mod=vendor -o ./go-link-check"
